// This index file was auto-generated by DotIndexGeneratorPlugin.
// To overwrite it, simply add an index.js file of your own.

export { default as dotIndexPlugin } from './dot-index-plugin'
export { default as __snapshots__ } from './__snapshots__'
export { default as testInput } from './test-input'
